nil stdin

diff --git a/files/zsh/bin/sd b/files/zsh/bin/sd
--- a/files/zsh/bin/sd
+++ b/files/zsh/bin/sd
@@ -10,6 +10,12 @@ then
   exit 1
 fi
 
+if [[ -t 0 ]]
+then
+  >&2 printf '%s\n' 'ERROR -- nil stdin'
+  exit 1
+fi
+
 
 SEARCH="$1"
 REPLACE="$2"
