globs

diff --git a/roles/posix/files/zsh/rc.d/fun/bin/cm b/roles/posix/files/zsh/rc.d/fun/bin/cm
--- a/roles/posix/files/zsh/rc.d/fun/bin/cm
+++ b/roles/posix/files/zsh/rc.d/fun/bin/cm
@@ -1,4 +1,4 @@
-#!/usr/bin/env -S -- bash -Eeuo pipefail -O dotglob -O nullglob -O failglob -O globstar
+#!/usr/bin/env -S -- bash -Eeuo pipefail -O dotglob -O nullglob -O extglob -O failglob -O globstar
 
 COLOURS=(green red blue white yellow cyan magenta black)
 COLOUR="${COLOURS[$((RANDOM % ${#COLOURS[@]}))]}"
