-

diff --git a/layers/posix/home/.local/bin/hx b/layers/posix/home/.local/bin/hx
--- a/layers/posix/home/.local/bin/hx
+++ b/layers/posix/home/.local/bin/hx
@@ -1,6 +1,7 @@
-#!/usr/bin/env -S -- bash -Eeu -o pipefail -O dotglob -O nullglob -O extglob -O globstar
+#!/usr/bin/env -S -- bash -Eeu -o pipefail -O dotglob -O nullglob -O extglob -O failglob -O globstar
 
 set -o pipefail
+shopt -u failglob
 
 OPT="$HOME/.local/opt/helix"
 
