globs

diff --git a/roles/posix/files/zsh/rc.d/shared/bin/pom b/roles/posix/files/zsh/rc.d/shared/bin/pom
--- a/roles/posix/files/zsh/rc.d/shared/bin/pom
+++ b/roles/posix/files/zsh/rc.d/shared/bin/pom
@@ -1,4 +1,4 @@
-#!/usr/bin/env -S -- bash -Eeuo pipefail -O dotglob -O nullglob -O failglob -O globstar
+#!/usr/bin/env -S -- bash -Eeuo pipefail -O dotglob -O nullglob -O extglob -O failglob -O globstar
 
 TTL="$1"
 NOW="$(date -- '+%s')"
