glob

diff --git a/roles/posix/files/zsh/rc.d/shared/bin/rgf b/roles/posix/files/zsh/rc.d/shared/bin/rgf
--- a/roles/posix/files/zsh/rc.d/shared/bin/rgf
+++ b/roles/posix/files/zsh/rc.d/shared/bin/rgf
@@ -1,4 +1,4 @@
-#!/usr/bin/env -S -- bash -Eeuo pipefail -O failglob -O globstar
+#!/usr/bin/env -S -- bash -Eeuo pipefail -O dotglob -O failglob -O globstar
 
 RG_ARGS="${_RG_ARGS:-}"
 
