printf

diff --git a/roles/posix/files/zsh/rc.d/shared/bin/sd b/roles/posix/files/zsh/rc.d/shared/bin/sd
--- a/roles/posix/files/zsh/rc.d/shared/bin/sd
+++ b/roles/posix/files/zsh/rc.d/shared/bin/sd
@@ -6,14 +6,14 @@ shopt -s nullglob globstar
 
 if [[ $# -lt 2 ]]
 then
-  >&2 printf '%s\n' 'ERROR -- missing args:
+  >&2 printf -- '%s\n' 'ERROR -- missing args:
   <search> <replacement>'
   exit 1
 fi
 
 if [[ -t 0 ]]
 then
-  >&2 printf '%s\n' 'ERROR -- nil stdin'
+  >&2 printf -- '%s\n' 'ERROR -- nil stdin'
   exit 1
 fi
 
diff --git a/roles/posix/files/zsh/rc.d/shared/bin/venv b/roles/posix/files/zsh/rc.d/shared/bin/venv
--- a/roles/posix/files/zsh/rc.d/shared/bin/venv
+++ b/roles/posix/files/zsh/rc.d/shared/bin/venv
@@ -57,11 +57,11 @@ case "$OP" in
 init)
   if [[ -d "$DEFAULT_VENV_PATH" ]]
   then
-    >&2 printf '%s\n' "Virtualenv already initialized"
+    >&2 printf -- '%s\n' "Virtualenv already initialized"
   else
     >&2 python3 -m venv "$DEFAULT_VENV_PATH"
     >&2 "$PY_EXE" <<< "$PYPROJ"
-    >&2 printf '%s\n' "Initialized Virtualenv"
+    >&2 printf -- '%s\n' "Initialized Virtualenv"
     venv on
   fi
   ;;
@@ -69,8 +69,8 @@ on)
   if [[ -f "$ACTIVATE" ]]
   then
     venv off
-    printf '%s\n' "source '$ACTIVATE'"
-    >&2 printf '%s\n' "Activated - $DEFAULT_VENV_PATH"
+    printf -- '%s\n' "source '$ACTIVATE'"
+    >&2 printf -- '%s\n' "Activated - $DEFAULT_VENV_PATH"
   else
     venv init
   fi
@@ -80,9 +80,9 @@ off)
   then
     true
   else
-    printf '%s\n' 'deactivate'
+    printf -- '%s\n' 'deactivate'
   fi
-  >&2 printf '%s\n' "Deactivating - $VIRTUAL_ENV"
+  >&2 printf -- '%s\n' "Deactivating - $VIRTUAL_ENV"
   ;;
 rm)
   if [[ -d "$DEFAULT_VENV_PATH" ]]
@@ -91,12 +91,12 @@ rm)
     then
       venv off
     fi
-    printf '%s\n' "rm -rf '$DEFAULT_VENV_PATH'"
+    printf -- '%s\n' "rm -rf '$DEFAULT_VENV_PATH'"
   fi
-  >&2 printf '%s\n' "Removed - $DEFAULT_VENV_PATH"
+  >&2 printf -- '%s\n' "Removed - $DEFAULT_VENV_PATH"
   ;;
 *)
-  >&2 printf '%s\n' "Invalid argument"
-  >&2 printf '%s\n' "venv - [on | off | rm]"
+  >&2 printf -- '%s\n' "Invalid argument"
+  >&2 printf -- '%s\n' "venv - [on | off | rm]"
   ;;
 esac
