sd

diff --git a/roles/posix/files/zsh/rc.d/shared/bin/sd b/roles/posix/files/zsh/rc.d/shared/bin/sd
--- a/roles/posix/files/zsh/rc.d/shared/bin/sd
+++ b/roles/posix/files/zsh/rc.d/shared/bin/sd
@@ -1,7 +1,4 @@
-#!/usr/bin/env -S -- bash
-
-set -u
-shopt -s failglob globstar
+#!/usr/bin/env -S -- bash -Eeuo pipefail -O failglob -O globstar
 
 if [[ $# -lt 2 ]]; then
   printf >&2 -- '%s\n' 'ERROR -- missing args:
@@ -29,10 +26,4 @@ ARGS=(
   "$SEARCH"
 )
 
-rg "${ARGS[@]}" </dev/stdin
-
-if [[ $? -eq 2 ]]; then
-  exit 1
-else
-  exit 0
-fi
+exec -- rg "${ARGS[@]}" </dev/stdin
