both globs

diff --git a/roles/posix/files/zsh/rc.d/shared/bin/sd b/roles/posix/files/zsh/rc.d/shared/bin/sd
--- a/roles/posix/files/zsh/rc.d/shared/bin/sd
+++ b/roles/posix/files/zsh/rc.d/shared/bin/sd
@@ -1,4 +1,4 @@
-#!/usr/bin/env -S -- bash -Eeuo pipefail -O dotglob -O failglob -O globstar
+#!/usr/bin/env -S -- bash -Eeuo pipefail -O dotglob -O nullglob -O failglob -O globstar
 
 if [[ $# -lt 2 ]]; then
   printf >&2 -- '%s\n' 'ERROR -- missing args:
