glob

diff --git a/roles/posix/files/zsh/rc.d/darwin/bin/nproc b/roles/posix/files/zsh/rc.d/darwin/bin/nproc
--- a/roles/posix/files/zsh/rc.d/darwin/bin/nproc
+++ b/roles/posix/files/zsh/rc.d/darwin/bin/nproc
@@ -1,3 +1,3 @@
-#!/usr/bin/env -S -- bash -Eeuo pipefail -O failglob -O globstar
+#!/usr/bin/env -S -- bash -Eeuo pipefail -O dotglob -O failglob -O globstar
 
 exec -- sysctl -n hw.physicalcpu
diff --git a/roles/posix/files/zsh/rc.d/shared/bin/hr b/roles/posix/files/zsh/rc.d/shared/bin/hr
--- a/roles/posix/files/zsh/rc.d/shared/bin/hr
+++ b/roles/posix/files/zsh/rc.d/shared/bin/hr
@@ -1,4 +1,4 @@
-#!/usr/bin/env -S -- bash -Eeuo pipefail -O failglob -O globstar
+#!/usr/bin/env -S -- bash -Eeuo pipefail -O dotglob -O failglob -O globstar
 
 WORD="${1-"#"}"
 COLS="${2:-"$(tput -- cols)"}"
