failglob

diff --git a/roles/posix/files/zsh/rc.d/tmux/bin/tmux-esc b/roles/posix/files/zsh/rc.d/tmux/bin/tmux-esc
--- a/roles/posix/files/zsh/rc.d/tmux/bin/tmux-esc
+++ b/roles/posix/files/zsh/rc.d/tmux/bin/tmux-esc
@@ -1,4 +1,4 @@
-#!/usr/bin/env -S -- bash -Eeuo pipefail -O nullglob -O globstar
+#!/usr/bin/env -S -- bash -Eeuo pipefail -O failglob -O globstar
 
 read -r -d '' -- AWK <<-'EOF' || true
 BEGIN { 
